# Generated by Django 5.1.5 on 2025-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_checklistbase_bottom_tool_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skill_matrix_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
