# Generated by Django 5.1.5 on 2025-04-23 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_defectcategory_operationnumber_defecttype_ftqrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDefectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ftq_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_defect_types",
                        to="main.ftqrecord",
                    ),
                ),
                (
                    "operation_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_defect_types",
                        to="main.operationnumber",
                    ),
                ),
            ],
        ),
    ]
