# Generated by Django 5.1.5 on 2025-04-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_customdefecttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftqrecord",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ftq_records",
                to="main.shift",
            ),
        ),
    ]
