# Generated by Django 5.1.5 on 2025-04-23 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_ftqrecord_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectrecord",
            name="defect_type_custom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.customdefecttype",
            ),
        ),
        migrations.AlterField(
            model_name="defectrecord",
            name="count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="defectrecord",
            name="defect_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.defecttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="defectrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("defect_type__isnull", False),
                        ("defect_type_custom__isnull", True),
                    ),
                    models.Q(
                        ("defect_type__isnull", True),
                        ("defect_type_custom__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_defect_type",
            ),
        ),
    ]
