# Generated by Django 5.1.5 on 2025-04-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_dtpmchecklistfma03_dtpmcheckresult_dtpmissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dtpmchecklistfma03",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dtpm_checklists",
                to="main.shift",
            ),
        ),
    ]
