# Generated by Django 5.1.5 on 2025-04-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_dtpmchecklistfma03_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dtpmchecklistfma03",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
