# Generated by Django 5.1.5 on 2025-04-25 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_dtpmchecklistfma03_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorPreventionCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("supervisor_approved", "Supervisor Approved"),
                            ("quality_approved", "Quality Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "current_model",
                    models.CharField(
                        choices=[("T6", "T6"), ("Gnome", "Gnome")],
                        max_length=10,
                        verbose_name="Current Running Model",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ep_operator_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quality_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ep_quality_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_prevention_checks",
                        to="main.shift",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ep_supervisor_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Prevention Check",
                "verbose_name_plural": "Error Prevention Checks",
                "ordering": ["-date", "shift"],
                "unique_together": {("date", "shift")},
            },
        ),
        migrations.CreateModel(
            name="ErrorPreventionMechanismStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ep_mechanism_id",
                    models.CharField(
                        choices=[
                            (
                                "FMA-03-35-M01_T6",
                                "FMA-03-35-M01(T6) / FMA-03-35-M09(Gnome)",
                            ),
                            ("FMA-03-35-M02", "FMA-03-35-M02 (T6/Gnome)"),
                            (
                                "FMA-03-35-M03",
                                "FMA-03-35-M03 (T6) / FMA-03-35-M10 (Gnome)",
                            ),
                            (
                                "FMA-03-35-M04",
                                "FMA-03-35-M04 (T6) / FMA-03-35-M11 (Gnome)",
                            ),
                            (
                                "FMA-03-35-M05",
                                "FMA-03-35-M05 (T6) / FMA-03-35-M12 (Gnome)",
                            ),
                            ("FMA-03-35-M06", "FMA-03-35-M06 (T6/Gnome)"),
                            ("FMA-03-35-M07", "FMA-03-35-M07 (T6/Gnome)"),
                            (
                                "FMA-03-35-M08",
                                "FMA-03-35-M08 (T6) / FMA-03-35-M13(Gnome)",
                            ),
                        ],
                        max_length=50,
                        verbose_name="EP Mechanism ID",
                    ),
                ),
                (
                    "is_working",
                    models.BooleanField(default=True, verbose_name="Working"),
                ),
                (
                    "alternative_method",
                    models.CharField(
                        default="100% Inspection By Operator",
                        max_length=100,
                        verbose_name="Alternative Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_not_applicable",
                    models.BooleanField(default=False, verbose_name="N/A"),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "ep_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanism_statuses",
                        to="main.errorpreventioncheck",
                    ),
                ),
            ],
            options={
                "ordering": ["ep_mechanism_id"],
                "unique_together": {("ep_check", "ep_mechanism_id")},
            },
        ),
    ]
