# Generated by Django 5.1.5 on 2025-04-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_errorpreventioncheck_errorpreventionmechanismstatus"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="errorpreventioncheck",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="errorpreventionmechanismstatus",
            unique_together=set(),
        ),
    ]
