# Generated by Django 5.1.5 on 2025-05-07 17:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_errorpreventioncheck_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dtpmcheckresult",
            name="image",
        ),
        migrations.CreateModel(
            name="DTPMCheckImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image showing the condition during check",
                        upload_to="dtpm/check_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order in which to display images"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.dtpmcheckresult",
                    ),
                ),
            ],
            options={
                "ordering": ["check_result", "image_order", "uploaded_at"],
                "unique_together": {("check_result", "image_order")},
            },
        ),
    ]
