# Generated by Django 5.1.5 on 2025-05-07 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_dtpmcheckresult_image_dtpmcheckimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dtpmcheckresult",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image showing the condition during check",
                null=True,
                upload_to="dtpm/check_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="DTPMCheckImage",
        ),
    ]
