# Generated by Django 5.1.5 on 2025-05-08 05:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_dtpmcheckresult_image_delete_dtpmcheckimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DTPMChecklistFMA03New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operated_dtpm_checklists_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dtpm_checklists_new",
                        to="main.shift",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_dtpm_checklists_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DTPM Checklist",
                "verbose_name_plural": "DTPM Checklists",
                "ordering": ["-date"],
                "unique_together": {("date", "shift")},
            },
        ),
        migrations.CreateModel(
            name="DTPMCheckResultNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkpoint_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "EMERGENCY push button is Working Properly"),
                            (
                                2,
                                "There should not be any air leakage & Lubrication unit mounting should not be loose and no oil spillage",
                            ),
                            (3, "All nuts and bolts should not be loose or free"),
                            (4, "Check all sensors for damage or looseness"),
                            (5, "Tower lamp & Tube light should be working properly"),
                            (
                                6,
                                "All indicators & push buttons should be working properly",
                            ),
                            (7, "Check Safety curtain working properly"),
                        ],
                        verbose_name="Checkpoint",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reference_image",
                    models.ImageField(
                        blank=True,
                        help_text="Reference image showing the correct condition",
                        null=True,
                        upload_to="dtpm/reference_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image showing the current condition during check",
                        null=True,
                        upload_to="dtpm/check_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="main.dtpmchecklistfma03new",
                    ),
                ),
            ],
            options={
                "ordering": ["checkpoint_number"],
                "unique_together": {("checklist", "checkpoint_number")},
            },
        ),
        migrations.CreateModel(
            name="DTPMIssueNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("action_taken", models.TextField(blank=True, null=True)),
                ("resolution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "issue_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dtpm/issue_images_new/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "resolution_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dtpm/resolution_images_new/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_dtpm_issues_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "check_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="main.dtpmcheckresultnew",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_dtpm_issues_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolved_dtpm_issues_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
