# Generated by Django 5.1.5 on 2025-05-09 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_dtpmchecklistfma03new_dtpmcheckresultnew_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ftqrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subgroupentry",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subgroupverification",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="checklistbase",
            name="shift",
        ),
        migrations.AlterField(
            model_name="shift",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="shift",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("day", "Day Shift (6 AM - 6 PM)"),
                    ("night", "Night Shift (6 PM - 6 AM)"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DailyVerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operator_notified", models.BooleanField(default=False)),
                ("supervisor_notified", models.BooleanField(default=False)),
                ("quality_notified", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_statuses",
                        to="main.shift",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="checklistbase",
            name="verification_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklists",
                to="main.dailyverificationstatus",
            ),
        ),
        migrations.AddField(
            model_name="ftqrecord",
            name="verification_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ftq_records",
                to="main.dailyverificationstatus",
            ),
        ),
        migrations.RemoveField(
            model_name="ftqrecord",
            name="shift",
        ),
    ]
