# Generated by Django 5.1.5 on 2025-05-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_ftqrecord_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="errorpreventioncheck",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Error Prevention Check",
                "verbose_name_plural": "Error Prevention Checks",
            },
        ),
        migrations.RemoveField(
            model_name="errorpreventioncheck",
            name="shift",
        ),
        migrations.AddField(
            model_name="errorpreventioncheck",
            name="verification_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="error_prevention_checks",
                to="main.dailyverificationstatus",
            ),
        ),
        migrations.AlterField(
            model_name="errorpreventioncheck",
            name="current_model",
            field=models.CharField(
                choices=[
                    ("P703", "P703"),
                    ("U704", "U704"),
                    ("FD", "FD"),
                    ("SA", "SA"),
                    ("Gnome", "Gnome"),
                ],
                max_length=10,
                verbose_name="Current Running Model",
            ),
        ),
    ]
