# Generated by Django 5.1.5 on 2025-05-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_errorpreventioncheck_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dtpmcheckresultnew",
            name="reference_image",
        ),
        migrations.RemoveField(
            model_name="dtpmcheckresultnew",
            name="result_image",
        ),
        migrations.RemoveField(
            model_name="dtpmissuenew",
            name="issue_image",
        ),
        migrations.RemoveField(
            model_name="dtpmissuenew",
            name="resolution_image",
        ),
        migrations.AddField(
            model_name="dtpmchecklistfma03new",
            name="verification_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dtpm_checklists",
                to="main.dailyverificationstatus",
            ),
        ),
    ]
