# Generated by Django 5.1.5 on 2025-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_remove_dtpmcheckresultnew_reference_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistbase",
            name="bottom_tool_id_status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checklistbase",
            name="top_tool_id_status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="retainer_part_no",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="umbrella_part_no",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="uv_assy_stage_id",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="uv_clip_part_no",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
    ]
