# Generated by Django 5.1.5 on 2025-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_checklistbase_bottom_tool_id_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistbase",
            name="retainer_part_no_status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checklistbase",
            name="umbrella_part_no_status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checklistbase",
            name="uv_assy_stage_id_status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checklistbase",
            name="uv_clip_part_no_status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NG", "NG")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="bottom_tool_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FMA-03-35-T06", "FMA-03-35-T06 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T08", "FMA-03-35-T08 (Gnome)"),
                ],
                max_length=100,
                null=True,
                verbose_name="Bottom Tool ID",
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="retainer_part_no",
            field=models.CharField(
                blank=True,
                choices=[
                    ("42001878", "42001878 (P703/U704/SA/FD)"),
                    ("42050758", "42050758 (Gnome)"),
                ],
                max_length=100,
                null=True,
                verbose_name="Retainer Part no",
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="top_tool_id",
            field=models.CharField(
                blank=True,
                choices=[("FMA-03-35-T05", "FMA-03-35-T05 (P703/U704/SA/FD/Gnome)")],
                max_length=100,
                null=True,
                verbose_name="Top Tool ID",
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="umbrella_part_no",
            field=models.CharField(
                blank=True,
                choices=[("25094588", "25094588 (P703/U704/SA/FD/Gnome)")],
                max_length=100,
                null=True,
                verbose_name="Umbrella Part No",
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="uv_assy_stage_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FMA-03-35-T07", "FMA-03-35-T07 (P703/U704/SA/FD)"),
                    ("FMA-03-35-T09", "FMA-03-35-T09 (Gnome)"),
                ],
                max_length=100,
                null=True,
                verbose_name="UV Assy Stage 1 ID",
            ),
        ),
        migrations.AlterField(
            model_name="checklistbase",
            name="uv_clip_part_no",
            field=models.CharField(
                blank=True,
                choices=[
                    ("42000829", "42000829 (P703/U704/SA/FD)"),
                    ("42000829", "42000829 (Gnome)"),
                ],
                max_length=100,
                null=True,
                verbose_name="UV Clip Part No",
            ),
        ),
    ]
