# Generated by Django 5.1.5 on 2025-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_checklistbase_retainer_part_no_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistbase",
            name="new_shift",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S1", "S1 - 6:30 AM to 6:30 PM"),
                    ("A", "A - 6:30 AM to 3:00 PM"),
                    ("G", "G - 8:30 AM to 5:00 PM"),
                    ("B", "B - 3:00 PM to 11:30 PM"),
                    ("C", "C - 11:30 PM to 6:30 AM"),
                    ("S2", "S2 - 6:30 PM to 6:30 AM"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
