# Generated by Django 5.1.5 on 2025-05-22 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_checklistbase_new_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubgroupEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.CharField(blank=True, max_length=200, null=True)),
                ("new_value", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="main.subgroupentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-edited_at"],
            },
        ),
    ]
