# Generated by Django 5.1.5 on 2025-05-29 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_ftqrecord_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='quality_certified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='quality_certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtpm_quality_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='quality_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='quality_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='quality_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtpm_quality_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtpm_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='supervisor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtpm_supervisor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DTPMVerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('supervisor_approve', 'Supervisor Approved'), ('supervisor_reject', 'Supervisor Rejected'), ('quality_certify', 'Quality Certified'), ('quality_reject', 'Quality Rejected')], max_length=20)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to='main.dtpmchecklistfma03new')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dtpm_verification_history',
                'ordering': ['-verified_at'],
            },
        ),
    ]
