# Generated by Django 5.1.5 on 2025-06-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_dtpmchecklistfma03new_quality_certified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroupentry',
            name='bin_contamination_check',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='umbrella_valve_assembly',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='uv_clip_pressing',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='uv_flow_value',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='uv_vacuum_test',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='workstation_clean',
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='bin_contamination_check_1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Bin Contamination Check Reading 1'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='bin_contamination_check_2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Bin Contamination Check Reading 2'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='bin_contamination_check_3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Bin Contamination Check Reading 3'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='bin_contamination_check_4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Bin Contamination Check Reading 4'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='bin_contamination_check_5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Bin Contamination Check Reading 5'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='umbrella_valve_assembly_1',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='Umbrella Valve Assembly Reading 1'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='umbrella_valve_assembly_2',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='Umbrella Valve Assembly Reading 2'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='umbrella_valve_assembly_3',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='Umbrella Valve Assembly Reading 3'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='umbrella_valve_assembly_4',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='Umbrella Valve Assembly Reading 4'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='umbrella_valve_assembly_5',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='Umbrella Valve Assembly Reading 5'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_clip_pressing_1',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='UV Clip Pressing Reading 1'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_clip_pressing_2',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='UV Clip Pressing Reading 2'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_clip_pressing_3',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='UV Clip Pressing Reading 3'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_clip_pressing_4',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='UV Clip Pressing Reading 4'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_clip_pressing_5',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, null=True, verbose_name='UV Clip Pressing Reading 5'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_flow_value_1',
            field=models.FloatField(blank=True, help_text='Reading 1: Recommended Range: 30-40 LPM', null=True, verbose_name='UV Flow Value Reading 1'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_flow_value_2',
            field=models.FloatField(blank=True, help_text='Reading 2: Recommended Range: 30-40 LPM', null=True, verbose_name='UV Flow Value Reading 2'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_flow_value_3',
            field=models.FloatField(blank=True, help_text='Reading 3: Recommended Range: 30-40 LPM', null=True, verbose_name='UV Flow Value Reading 3'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_flow_value_4',
            field=models.FloatField(blank=True, help_text='Reading 4: Recommended Range: 30-40 LPM', null=True, verbose_name='UV Flow Value Reading 4'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_flow_value_5',
            field=models.FloatField(blank=True, help_text='Reading 5: Recommended Range: 30-40 LPM', null=True, verbose_name='UV Flow Value Reading 5'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_vacuum_test_1',
            field=models.FloatField(blank=True, help_text='Reading 1: Recommended Range: -35 to -43 kPa', null=True, verbose_name='UV Vacuum Test Reading 1'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_vacuum_test_2',
            field=models.FloatField(blank=True, help_text='Reading 2: Recommended Range: -35 to -43 kPa', null=True, verbose_name='UV Vacuum Test Reading 2'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_vacuum_test_3',
            field=models.FloatField(blank=True, help_text='Reading 3: Recommended Range: -35 to -43 kPa', null=True, verbose_name='UV Vacuum Test Reading 3'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_vacuum_test_4',
            field=models.FloatField(blank=True, help_text='Reading 4: Recommended Range: -35 to -43 kPa', null=True, verbose_name='UV Vacuum Test Reading 4'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='uv_vacuum_test_5',
            field=models.FloatField(blank=True, help_text='Reading 5: Recommended Range: -35 to -43 kPa', null=True, verbose_name='UV Vacuum Test Reading 5'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='workstation_clean_1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Workstation Clean Reading 1'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='workstation_clean_2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Workstation Clean Reading 2'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='workstation_clean_3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Workstation Clean Reading 3'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='workstation_clean_4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Workstation Clean Reading 4'),
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='workstation_clean_5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Workstation Clean Reading 5'),
        ),
    ]
