# Generated by Django 5.1.5 on 2025-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_subgroupentry_bin_contamination_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroupentry',
            name='workstation_clean_1',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='workstation_clean_2',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='workstation_clean_3',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='workstation_clean_4',
        ),
        migrations.RemoveField(
            model_name='subgroupentry',
            name='workstation_clean_5',
        ),
        migrations.AddField(
            model_name='subgroupentry',
            name='workstation_clean',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Workstation Clean'),
        ),
        migrations.AlterField(
            model_name='dtpmcheckresultnew',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('NG', 'NG')], default='NG', max_length=2, verbose_name='Status'),
        ),
    ]
