# Generated by Django 5.1.5 on 2025-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_subgroupentry_workstation_clean_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistbase',
            name='shift',
            field=models.CharField(blank=True, choices=[('S1', 'S1 - 6:30 AM to 6:30 PM'), ('A', 'A - 6:30 AM to 3:00 PM'), ('G', 'G - 8:30 AM to 5:00 PM'), ('B', 'B - 3:00 PM to 11:30 PM'), ('C', 'C - 11:30 PM to 6:30 AM'), ('S2', 'S2 - 6:30 PM to 6:30 AM')], editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='checklist_shift',
            field=models.CharField(blank=True, choices=[('S1', 'S1 - 6:30 AM to 6:30 PM'), ('A', 'A - 6:30 AM to 3:00 PM'), ('G', 'G - 8:30 AM to 5:00 PM'), ('B', 'B - 3:00 PM to 11:30 PM'), ('C', 'C - 11:30 PM to 6:30 AM'), ('S2', 'S2 - 6:30 PM to 6:30 AM')], max_length=10, null=True, verbose_name='Shift from Checklist'),
        ),
        migrations.AddField(
            model_name='dtpmchecklistfma03new',
            name='current_model',
            field=models.CharField(blank=True, choices=[('P703', 'P703'), ('U704', 'U704'), ('FD', 'FD'), ('SA', 'SA'), ('Gnome', 'Gnome')], max_length=10, null=True, verbose_name='Current Running Model'),
        ),
        migrations.AddField(
            model_name='errorpreventioncheck',
            name='shift',
            field=models.CharField(blank=True, choices=[('S1', 'S1 - 6:30 AM to 6:30 PM'), ('A', 'A - 6:30 AM to 3:00 PM'), ('G', 'G - 8:30 AM to 5:00 PM'), ('B', 'B - 3:00 PM to 11:30 PM'), ('C', 'C - 11:30 PM to 6:30 AM'), ('S2', 'S2 - 6:30 PM to 6:30 AM')], max_length=10, null=True, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='errorpreventioncheck',
            name='current_model',
            field=models.CharField(blank=True, choices=[('P703', 'P703'), ('U704', 'U704'), ('FD', 'FD'), ('SA', 'SA'), ('Gnome', 'Gnome')], max_length=10, null=True, verbose_name='Current Running Model'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('S1', 'S1 - 6:30 AM to 6:30 PM'), ('A', 'A - 6:30 AM to 3:00 PM'), ('G', 'G - 8:30 AM to 5:00 PM'), ('B', 'B - 3:00 PM to 11:30 PM'), ('C', 'C - 11:30 PM to 6:30 AM'), ('S2', 'S2 - 6:30 PM to 6:30 AM')], max_length=10),
        ),
    ]
