# Generated by Django 5.1.5 on 2025-06-11 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_checklistbase_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPreventionCheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('supervisor_verified', 'Supervisor Verified'), ('quality_verified', 'Quality Verified'), ('rejected', 'Rejected')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ep_check_changes', to=settings.AUTH_USER_MODEL)),
                ('ep_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.errorpreventioncheck')),
            ],
            options={
                'verbose_name': 'EP Check History',
                'verbose_name_plural': 'EP Check Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorPreventionMechanismHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanism_changes', to=settings.AUTH_USER_MODEL)),
                ('mechanism_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.errorpreventionmechanismstatus')),
            ],
            options={
                'verbose_name': 'Mechanism Status History',
                'verbose_name_plural': 'Mechanism Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
