# Generated by Django 5.1.5 on 2025-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_errorpreventioncheckhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftqrecord',
            name='production_per_shift',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Production Data/Shift'),
        ),
    ]
