# Generated by Django 5.1.5 on 2025-10-02 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_subgroupfrequencyconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistDynamicValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_values",
                        to="main.checklistbase",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.checksheetcontentconfig",
                    ),
                ),
            ],
            options={
                "unique_together": {("checklist", "parameter")},
            },
        ),
    ]
