# Generated by Django 5.1.5 on 2025-10-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_checklistdynamicvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorPreventionMechanism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mechanism_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="EP Mechanism ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full description of the EP mechanism",
                        verbose_name="Mechanism Description",
                    ),
                ),
                (
                    "applicable_models",
                    models.CharField(
                        help_text="Comma-separated list of models (e.g., P703,U704,SA,FD or Gnome)",
                        max_length=100,
                        verbose_name="Applicable Models",
                    ),
                ),
                (
                    "is_currently_working",
                    models.BooleanField(
                        default=True,
                        help_text="Admin-controlled: Is this mechanism currently functional?",
                        verbose_name="Currently Working",
                    ),
                ),
                (
                    "default_alternative_method",
                    models.CharField(
                        default="100% Inspection By Operator",
                        max_length=200,
                        verbose_name="Default Alternative Method",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which to display this mechanism",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this mechanism currently in use?",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Error Prevention Mechanism (Master)",
                "verbose_name_plural": "Error Prevention Mechanisms (Master)",
                "ordering": ["display_order", "mechanism_id"],
            },
        ),
        migrations.AlterModelOptions(
            name="errorpreventionmechanismstatus",
            options={
                "ordering": ["mechanism__display_order", "mechanism__mechanism_id"],
                "verbose_name": "Mechanism Status",
                "verbose_name_plural": "Mechanism Statuses",
            },
        ),
        migrations.AddField(
            model_name="errorpreventionmechanismstatus",
            name="last_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorpreventionmechanismstatus",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_mechanism_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="errorpreventionmechanismstatus",
            name="alternative_method",
            field=models.CharField(
                default="100% Inspection By Operator",
                help_text="Admin-controlled via master mechanism",
                max_length=200,
                verbose_name="Alternative Method",
            ),
        ),
        migrations.AlterField(
            model_name="errorpreventionmechanismstatus",
            name="comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="Operator Comments"
            ),
        ),
        migrations.AlterField(
            model_name="errorpreventionmechanismstatus",
            name="ep_mechanism_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                null=True,
                verbose_name="EP Mechanism ID (Legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="errorpreventionmechanismstatus",
            name="is_not_applicable",
            field=models.BooleanField(
                default=False,
                help_text="Check if not applicable for this model",
                verbose_name="N/A",
            ),
        ),
        migrations.AlterField(
            model_name="errorpreventionmechanismstatus",
            name="is_working",
            field=models.BooleanField(
                default=True,
                help_text="Admin-controlled via master mechanism",
                verbose_name="Working",
            ),
        ),
        migrations.AlterField(
            model_name="errorpreventionmechanismstatus",
            name="status",
            field=models.CharField(
                choices=[("OK", "OK"), ("NG", "NG")],
                help_text="Operator selects OK or NG",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="errorpreventionmechanismstatus",
            name="mechanism",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_statuses",
                to="main.errorpreventionmechanism",
                verbose_name="EP Mechanism",
            ),
        ),
    ]
