# Generated by Django 5.1.5 on 2025-10-04 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_errorpreventionmechanism_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DTPMCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkpoint_number",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Checkpoint Number"
                    ),
                ),
                (
                    "title_english",
                    models.CharField(max_length=500, verbose_name="Title (English)"),
                ),
                (
                    "title_hindi",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Title (Hindi)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "reference_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dtpm_checkpoints/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "gif"]
                            )
                        ],
                        verbose_name="Reference Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to disable this checkpoint",
                        verbose_name="Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order in which to display this checkpoint",
                        verbose_name="Display Order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DTPM Checkpoint",
                "verbose_name_plural": "DTPM Checkpoints",
                "ordering": ["order", "checkpoint_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="dtpmcheckresultnew",
            options={
                "ordering": ["checkpoint__order", "checkpoint__checkpoint_number"]
            },
        ),
        migrations.AlterModelOptions(
            name="dtpmverificationhistory",
            options={
                "ordering": ["-verified_at"],
                "verbose_name": "DTPM Verification History",
                "verbose_name_plural": "DTPM Verification Histories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dtpmchecklistfma03new",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dtpmchecklistfma03new",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("supervisor_approved", "Supervisor Approved"),
                    ("quality_certified", "Quality Certified"),
                    ("rejected", "Rejected"),
                    ("quality_rejected", "Quality Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="dtpmverificationhistory",
            table=None,
        ),
        migrations.AlterUniqueTogether(
            name="dtpmcheckresultnew",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dtpmcheckresultnew",
            name="checkpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_results",
                to="main.dtpmcheckpoint",
                verbose_name="Checkpoint",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dtpmcheckresultnew",
            unique_together={("checklist", "checkpoint")},
        ),
        migrations.RemoveField(
            model_name="dtpmcheckresultnew",
            name="checkpoint_number",
        ),
    ]
