# Generated by Django 5.1.5 on 2025-10-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_dtpmcheckpoint_alter_dtpmcheckresultnew_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBasedDefectEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.TimeField(
                        help_text="Time when this defect was observed",
                        verbose_name="Time Recorded",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        help_text="Number of defects at this time",
                        verbose_name="Defect Count",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Time-Based Defect Entry",
                "verbose_name_plural": "Time-Based Defect Entries",
                "ordering": ["recorded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="ftqrecord",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="defectrecord",
            name="exactly_one_defect_type",
        ),
        migrations.RemoveField(
            model_name="ftqrecord",
            name="total_defects",
        ),
        migrations.AddField(
            model_name="timebaseddefectentry",
            name="defect_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.defecttype",
            ),
        ),
        migrations.AddField(
            model_name="timebaseddefectentry",
            name="defect_type_custom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.customdefecttype",
            ),
        ),
        migrations.AddField(
            model_name="timebaseddefectentry",
            name="ftq_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_based_defects",
                to="main.ftqrecord",
            ),
        ),
    ]
