# Generated by Django 5.1.5 on 2025-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_timebaseddefectentry_alter_ftqrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroupentry",
            name="bin_contamination_check_1_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bin Contamination 1 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="bin_contamination_check_2_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bin Contamination 2 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="bin_contamination_check_3_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bin Contamination 3 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="bin_contamination_check_4_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bin Contamination 4 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="bin_contamination_check_5_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bin Contamination 5 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="umbrella_valve_assembly_1_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Umbrella Valve 1 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="umbrella_valve_assembly_2_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Umbrella Valve 2 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="umbrella_valve_assembly_3_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Umbrella Valve 3 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="umbrella_valve_assembly_4_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Umbrella Valve 4 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="umbrella_valve_assembly_5_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Umbrella Valve 5 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_clip_pressing_1_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Clip Pressing 1 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_clip_pressing_2_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Clip Pressing 2 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_clip_pressing_3_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Clip Pressing 3 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_clip_pressing_4_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Clip Pressing 4 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_clip_pressing_5_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Clip Pressing 5 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_flow_value_1_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Flow Value 1 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_flow_value_2_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Flow Value 2 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_flow_value_3_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Flow Value 3 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_flow_value_4_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Flow Value 4 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_flow_value_5_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Flow Value 5 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_vacuum_test_1_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Vacuum Test 1 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_vacuum_test_2_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Vacuum Test 2 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_vacuum_test_3_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Vacuum Test 3 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_vacuum_test_4_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Vacuum Test 4 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="uv_vacuum_test_5_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="UV Vacuum Test 5 Comment"
            ),
        ),
        migrations.AddField(
            model_name="subgroupentry",
            name="workstation_clean_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Workstation Clean Comment"
            ),
        ),
    ]
