# Generated by Django 5.1.5 on 2025-10-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_subgroupentry_bin_contamination_check_1_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklistbase",
            name="good_bad_master_verification",
        ),
        migrations.RemoveField(
            model_name="checklistbase",
            name="master_verification_lvdt",
        ),
        migrations.RemoveField(
            model_name="checklistbase",
            name="tool_alignment",
        ),
    ]
