# Generated by Django 5.1.5 on 2025-10-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_remove_checklistbase_good_bad_master_verification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklistbase",
            name="error_proofing_verification",
        ),
    ]
