# Generated by Django 5.1.5 on 2025-10-23 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_remove_checklistbase_error_proofing_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Checksheet Name"
                    ),
                ),
                (
                    "name_hindi",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Checksheet Name (Hindi)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_models",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated model names (e.g., P703,U704) or leave blank for all models",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_checksheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checksheet Template",
                "verbose_name_plural": "Checksheet Templates",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChecksheetResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("supervisor_approved", "Supervisor Approved"),
                            ("quality_approved", "Quality Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("supervisor_approved_at", models.DateTimeField(blank=True, null=True)),
                ("quality_approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "checksheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="main.checksheet",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_checksheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quality_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_approved_checksheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisor_approved_checksheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checksheet_responses",
                        to="main.dailyverificationstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checksheet Response",
                "verbose_name_plural": "Checksheet Responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecksheetSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Section Name")),
                (
                    "name_hindi",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Section Name (Hindi)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Section Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "checksheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="main.checksheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checksheet Section",
                "verbose_name_plural": "Checksheet Sections",
                "ordering": ["checksheet", "order", "name"],
                "unique_together": {("checksheet", "name")},
            },
        ),
        migrations.CreateModel(
            name="ChecksheetField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=300, verbose_name="Field Label")),
                (
                    "label_hindi",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Field Label (Hindi)"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("number", "Number Input"),
                            ("decimal", "Decimal Input"),
                            ("dropdown", "Dropdown Select"),
                            ("ok_nok", "OK/NOK"),
                            ("yes_no", "Yes/No"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("datetime", "Date & Time"),
                            ("checkbox", "Checkbox"),
                            ("textarea", "Text Area"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="For dropdown fields, enter choices separated by commas",
                        verbose_name="Choices (comma-separated)",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Required Field"),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Minimum Value"
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Maximum Value"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Unit (e.g., bar, kPa, LPM)",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Help Text"
                    ),
                ),
                (
                    "help_text_hindi",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Help Text (Hindi)"
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Default Value"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Placeholder Text"
                    ),
                ),
                (
                    "auto_fill_based_on_model",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this field will be auto-filled based on the selected model",
                        verbose_name="Auto-fill based on selected model",
                    ),
                ),
                (
                    "model_value_mapping",
                    models.JSONField(
                        blank=True,
                        help_text='JSON format: {"P703": "value1", "U704": "value2"}',
                        null=True,
                        verbose_name="Model Value Mapping",
                    ),
                ),
                (
                    "has_status_field",
                    models.BooleanField(
                        default=False,
                        help_text="Add an additional OK/NOK status field",
                        verbose_name="Has Status Field (OK/NOK)",
                    ),
                ),
                (
                    "requires_comment_if_nok",
                    models.BooleanField(
                        default=False, verbose_name="Require comment if NOK/No"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="main.checksheetsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checksheet Field",
                "verbose_name_plural": "Checksheet Fields",
                "ordering": ["section", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ChecksheetFieldResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Field Value")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOK", "NOK")],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                ("filled_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.checksheetfield",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_responses",
                        to="main.checksheetresponse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Response",
                "verbose_name_plural": "Field Responses",
                "unique_together": {("response", "field")},
            },
        ),
    ]
