# Generated by Django 5.1.5 on 2025-10-23 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_checksheet_checksheetresponse_checksheetsection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checksheetfield",
            name="auto_fill_based_on_model",
            field=models.BooleanField(
                default=False, verbose_name="Auto-fill based on selected model"
            ),
        ),
        migrations.AlterField(
            model_name="checksheetfield",
            name="has_status_field",
            field=models.BooleanField(
                default=False, verbose_name="Has Status Field (OK/NOK)"
            ),
        ),
        migrations.AlterField(
            model_name="checksheetfield",
            name="model_value_mapping",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Model Value Mapping"
            ),
        ),
        migrations.AlterField(
            model_name="checksheetresponse",
            name="verification_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checksheet_responses",
                to="main.dailyverificationstatus",
            ),
        ),
    ]
