# Generated by Django 5.1.5 on 2025-10-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_alter_checksheetfield_auto_fill_based_on_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubgroupCategoryFrequencyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("P703", "P703"),
                            ("U704", "U704"),
                            ("FD", "FD"),
                            ("SA", "SA"),
                            ("Gnome", "Gnome"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("uv_vacuum_test", "UV Vacuum Test"),
                            ("uv_flow_value", "UV Flow Value"),
                            ("umbrella_valve_assembly", "Umbrella Valve Assembly"),
                            ("uv_clip_pressing", "UV Clip Pressing"),
                            ("workstation_cleanliness", "Workstation Cleanliness"),
                            ("bin_contamination_check", "Bin Contamination Check"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "frequency_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Frequency in minutes (e.g., 60 = every hour, 120 = every 2 hours)",
                    ),
                ),
                (
                    "max_readings_per_shift",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of readings for this category per shift",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subgroup Category Frequency Config",
                "verbose_name_plural": "Subgroup Category Frequency Configs",
                "ordering": ["model_name", "category"],
                "unique_together": {("model_name", "category")},
            },
        ),
    ]
