# Generated by Django 5.1.5 on 2025-10-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_subgroupcategoryfrequencyconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubgroupCategoryFrequencyConfig",
        ),
    ]
