# Generated by Django 5.1.5 on 2025-10-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_parametergroupconfig_parametergroupentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_flow_value_1_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_flow_value_2_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_flow_value_3_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_flow_value_4_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_flow_value_5_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_vacuum_test_1_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_vacuum_test_2_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_vacuum_test_3_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_vacuum_test_4_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupentry",
            name="uv_vacuum_test_5_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
