# Generated by Django 5.1.5 on 2025-10-29 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_parametergroupentry_uv_flow_value_1_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterGroupVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("supervisor", "Shift Supervisor"),
                            ("quality", "Quality Supervisor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Verification Comment"
                    ),
                ),
                (
                    "parameter_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="main.parametergroupentry",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parameter_group_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter Group Verification",
                "verbose_name_plural": "Parameter Group Verifications",
                "ordering": ["-verified_at"],
                "unique_together": {("parameter_entry", "verification_type")},
            },
        ),
    ]
