# Generated by Django 5.1.5 on 2025-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_parametergroupverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametergroupconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="parametergroupconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
