# Generated by Django 5.1.5 on 2025-10-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_parametergroupconfig_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checksheetcontentconfig",
            options={"ordering": ["model_name", "section", "order"]},
        ),
        migrations.AddField(
            model_name="checksheetcontentconfig",
            name="section",
            field=models.CharField(
                choices=[
                    ("initial_setup", "Initial Setup"),
                    ("standard_measurements", "Standard Measurements"),
                    ("status_checks", "Status Checks"),
                    ("ids_part_numbers", "IDs and Part Numbers"),
                    ("model_specific", "Model-Specific Parameters"),
                ],
                default="model_specific",
                max_length=30,
                null=True,
                verbose_name="Section",
            ),
        ),
        migrations.AlterField(
            model_name="checksheetcontentconfig",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order within section"
            ),
        ),
    ]
