# Generated by Django 5.1.5 on 2025-10-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_alter_checksheetcontentconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorpreventionmechanism",
            name="verification_method",
            field=models.TextField(
                default="Start the machine with master and judgement will given by machine",
                help_text="English verification method description",
                verbose_name="Verification Method (English)",
            ),
        ),
        migrations.AddField(
            model_name="errorpreventionmechanism",
            name="verification_method_hindi",
            field=models.TextField(
                blank=True,
                default="मास्टर के साथ मशीन शुरू करें और मशीन द्वारा निर्णय दिया जाएगा",
                help_text="Hindi verification method description",
                verbose_name="Verification Method (Hindi)",
            ),
        ),
    ]
