# Generated by Django 5.1.5 on 2025-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SopDisplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="screen_name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
