# Generated by Django 5.1.5 on 2025-05-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SopDisplay', '0002_station_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
