# Generated by Django 5.1.5 on 2025-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SopDisplay', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='screen_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
